# as followed from https://swimburger.net/blog/dotnet/how-to-deploy-blazor-webassembly-to-digitalocean-app-platform

FROM mcr.microsoft.com/dotnet/sdk:5.0
WORKDIR /app

COPY MatchingNeedsClient.csproj MatchingNeedsClient.csproj
RUN dotnet restore MatchingNeedsClient.csproj
COPY . .
RUN dotnet publish -c Release -o /output ---restore --nologo