name: matchingneeds
static_sites:
- name: site
  github:
    repo: danielcomboni/MatchingNeedsClient
    branch: master
    deploy_on_push: true
  dockerfile_path: Dockerfile.build 
  output_dir: /output/wwwroot
  index_document: index.html
  catchall_document: index.html